[workspace]
members = ["lib"]

[package]
name = "jj"
version = "0.1.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2018"

[dependencies.jj-lib]
path = "lib"

[dependencies]
blake2 = "0.9.1"
bytes = "1.0.0"
chrono = "0.4.19"
clap = "2.33.3"
config = "0.10.1"
criterion = "0.3.3"
diff = "0.1.12"
dirs = "3.0.1"
git2 = "0.13.14"
hex = "0.4.2"
indoc = "1.0.3"
pest = "2.1.3"
pest_derive = "2.1.0"
protobuf = { version = "2.18.1", features = ["with-bytes"] }
protobuf-codegen-pure = "2.18.1"
serde_json = "1.0.60"
tempfile = "3.1.0"
thiserror = "1.0.22"
uuid = { version = "0.8.1", features = ["v4"] }
zstd = "0.6.0"

[dev-dependencies]
test-case = "1.0.0"
regex = "1.4.2"
