[package]
name = "jujutsu"
version = "0.2.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "jj"
path = "src/main.rs"

[workspace]
members = ["lib"]

[dependencies]
blake2 = "0.9.2"
bytes = "1.1.0"
chrono = "0.4.19"
clap = { version = "3.0.4", features = ["cargo"] }
clap_complete = "3.0.2"
config = "0.11.0"
criterion = "0.3.5"
dirs = "4.0.0"
git2 = "0.13.24"
hex = "0.4.3"
indoc = "1.0.3"
itertools = "0.10.1"
jujutsu-lib = { version = "=0.2.0", path = "lib"}
maplit = "1.0.2"
pest = "2.1.3"
pest_derive = "2.1.0"
protobuf = { version = "2.25.2", features = ["with-bytes"] }
protobuf-codegen-pure = "2.25.2"
rand = "0.8.4"
serde_json = "1.0.72"
tempfile = "3.2.0"
textwrap = "0.14.2"
thiserror = "1.0.30"
uuid = { version = "0.8.2", features = ["v4"] }
zstd = "0.9.0"

[dev-dependencies]
test-case = "1.2.1"
regex = "1.5.4"
