[workspace]
members = ["lib"]

[package]
name = "jj"
version = "0.1.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2018"

[dependencies.jj-lib]
path = "lib"

[dependencies]
blake2 = "0.8"
bytes = "0.5"
chrono = "0.4"
clap = "2.33"
config = "0.10"
criterion = "0.3.2"
diff = "0.1"
dirs = "2.0"
git2 = "0.13"
hex = "0.4"
indoc = "1.0"
pest = "2.1"
pest_derive = "2.1"
protobuf = { version = "2.12", features = ["with-bytes"] }
protobuf-codegen-pure = "2.12"
serde_json = "1.0"
tempfile = "3.1"
uuid = { version = "0.8", features = ["v4"] }
zstd = "0.5"

[dev-dependencies]
test-case = "1.0.0"
regex = "1.3.9"
